# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_flatpages', '0002_auto_20160517_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsflatpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'pages', verbose_name='Image'),
        ),
    ]
